/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 5b00068567fe224f96a537853aa16836)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	DEV_MODE: string;
	MAILBOX: DurableObjectNamespace<import("./src/index").Mailbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Mailbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEV_MODE">> {}
}
